---
# My vars:
packages:
  - clustershell
  - htop
  - vim
  - nmap
  - wireshark

# Vars for geerligguy.containerd
containerd_service_state: started
containerd_service_enabled: true

containerd_config_cgroup_driver_systemd: true

# Vars for geerlingguy.kubernetes
kubernetes_version: '1.33'
kubernetes_allow_pods_on_control_plane: true