---
# Run basic tasks and pre-k8s prep
# - hosts: aspen
#   roles:
#   - preflight
#   - epilogue

# # K8s containerd and kubernetes installs
# - hosts: aspen
#   become: true
#   roles:
#     - geerlingguy.containerd
#     - geerlingguy.kubernetes
  
# # K8s post-install configuration
# - hosts: aspen
#   roles:
#   - role: midflight

# Install Slurm
- hosts: aspen
  become: true
  roles:
    - ansible-role-slurm

# Slurm post-install configuration
- hosts: aspen
  roles:
    - epilogue