---
- name: Remove package that auto-enables swap on ZRAM
  become: true
  ansible.builtin.dnf:
    name: "zram-generator-defaults"
    state: absent

- name: Disable swap
  become: true
  ansible.builtin.command:
    cmd: swapoff -a
  changed_when: true

- name: Set IP Forwarding in /proc
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
