---
- name: Initial configuration
  ansible.builtin.include_tasks: standup.yml

- name: Prep control nodes
  ansible.builtin.include_tasks: controller.yml
  when: kubernetes_role == 'control_plane'

- name: Prep compute nodes
  ansible.builtin.include_tasks: node.yml

- name: Run prep tasks for Kubernetes
  ansible.builtin.include_tasks: k8s.yml

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Reexec systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reexec: true
