---
- name: Open port 6443 for kubelet
  become: true
  ansible.posix.firewalld:
    port: 6443/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Open port 10250 for kubelet
  become: true
  ansible.posix.firewalld:
    port: 10250/tcp
    permanent: true
    state: enabled
    immediate: true