---
- name: Place SSH Key
  ansible.posix.authorized_key:
    user: vhafener
    state: present
    key: "{{ lookup('file', '/home/vhafener/.ssh/id_ed25519.pub') }}"

- name: Place /etc/hosts
  become: true
  ansible.builtin.copy:
    src: /etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Run updates
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
    update_only: true

- name: Install packages
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    "{{ packages }}"

# - name: Fix LVS sizing # Default fedora does strange, strange things with your LVM setup
#   become: true
#   community.general.lvol:
#     vg: fedora
#     lv: root
#     size: 221G
