---
- name: Add Slurm LD_LIBRARY_PATH to user's homedir bashrc
  ansible.builtin.lineinfile:
    path: /home/vhafener/.bashrc
    state: present
    insertafter: "# .bashrc"
    line: "export LD_LIBRARY_PATH=/usr/lib/slurm"

- name: Run ldconfig after library install
  become: true
  ansible.builtin.command:
    cmd: ldconfig
  changed_when: true

- name: Fix directory permissions in Slurm directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    recurse: true
  loop:
    - /usr/lib/slurm

- name: Fix directory permissions in Slurm conf dir
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: slurm
    group: slurm
    mode: '0755'
    recurse: true
  loop:
    - /etc/slurm
